name: minerl_challenge
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - pip
  # - pytorch
  # - torchvision
  # - cudatoolkit=10.0
  - mkl
  - numpy
  - tensorflow-gpu=1.14
  # - tensorflow=1.14
