name: minerl_challenge
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - pip
  # - pytorch
  # - torchvision
  # - cudatoolkit=10.0
  - mkl
  - numpy
  # - tensorflow-gpu=1.14
  - tensorflow=1.14
  - pip:
    - git+git://github.com/Sohojoe/ml-agents-envs-python@master
    - git+git://github.com/Sohojoe/ml-agents-python@master
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib==3.0.3
    - opencv-python
    - pyro4
    - packaging
    - docopt
    - pyyaml
    - h5py>=2.9.0

