default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

MineRLObtainDiamondDense-v0:
MineRLObtainDiamond-v0:
    max_steps: 10.0e5
    batch_size: 64
    buffer_size: 2048
    # beta: 1.0e-2
    num_epoch: 10
    learning_rate: 1.0e-4
    hidden_units: 256
    summary_freq: 5000
    time_horizon: 12000
    num_layers: 2
    beta: 0.0
    # beta: 1.0e-2
    vis_encode_type: simple
    use_recurrent: true
    sequence_length: 1024
    memory_size: 32
    # normalize: true
    # pretraining:
    #     demo_path: MineRLTreechop-v0
    #     strength: 0.5
    #     steps: 10000
    reward_signals:
        extrinsic:
            strength: 1
            gamma: 0.995
        gail:
            strength: 0.03
            gamma: 0.995
            # encoding_size: 128
            encoding_size: 256
            use_actions: true
            # use_vail: true
            demo_path: MineRLObtainDiamond-v0
