default:
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_update: 1
    train_interval: 1
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

MineRLTreechop-v0:
    summary_freq: 2000
    time_horizon: 1000
    batch_size: 64
    buffer_init_steps: 10000
    buffer_size: 500000
    hidden_units: 128
    num_layers: 4
    train_interval: 2
    init_entcoef: 0.03
    # max_steps: 10.0e5
    max_steps: 80.0e5
    sequence_length: 64
    tau: 0.01
    learning_rate: 1e-4
    use_recurrent: true
    # vis_encode_type: resnet
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.995
        gail:
            strength: 0.03
            gamma: 0.995
            # encoding_size: 128
            use_actions: true
            use_vail: true
            demo_path: MineRLTreechop-v0


MineRLNavigateDense-v0:
    summary_freq: 2000
    time_horizon: 64
    batch_size: 64
    buffer_init_steps: 10000
    buffer_size: 500000
    hidden_units: 128
    num_layers: 2
    init_entcoef: 0.15
    max_steps: 5.0e5
    sequence_length: 64
    tau: 0.01
    # learning_rate: 1e-4
    use_recurrent: true
    # vis_encode_type: resnet
    # pretraining:
    #     demo_path: MineRLNavigateDense-v0
    #     strength: 0.5
    #     steps: 10000    
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        gail:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
            # use_actions: true
            demo_path: MineRLNavigateDense-v0
